title:        "QosimD OS Page"
author:       "Qosim Ariqoh Daffa"

navbarlinks:
- navbar:     "Home"
  link:       "/"
- navbar:     "Links"
  link:       "/LINKS/"
- navbar:     "Tips"
  link:       "/TIPS/"
- navbar:     "Log"
  link:       "https://qosimd25.github.io/os212/TXT/mylog.txt"
- navbar:     "Github"
  link:       "https://github.com/qosimd25/"

github:
- metadata
