version:     "---"
copyright:   "2021-2021"
description:
  Github OS Page
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "Log"
  link:      "https://qosimd25.github.io/os212/TXT/mylog.txt"
- navbar:    "GitHub"
  link:      "https://github.com/qosimd25/"
title:       "Operating System 2021-2 (os212)"
lang:        "en-US"
author:      "Qosim A.D."
address:     ""
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://qosimd25.github.io/os212"
urlcontact:       ""
urlgithub:        "https://github.com/qosimd25/os212"
