version:      "---"
copyright:    "2021-2021"
description:
  GitHub Page
deisclaimer:
  I have spoken
keywords:     "jekyll, testing"
navbarlinks:
- navbar:     "Home"
  link:       "/"
- navbar:     "Links"
  link:       "/LINKS/"
- navbar:     "Tips"
  link:       "/TIPS/"
- navbar:     "Log"
  link:       "https://qosimd25.github.io/os212/TXT/mylog.txt"
- navbar:     "Github"
  link:       "https://github.com/qosimd25/"

title:        "QosimD OS212 Page"
lang:         "en-us"
author:       "Qosim Ariqoh Daffa"
sitemap:      "true"
markdown:     "kramdown"
default:
- scope:
    path:     ""
  values:
    layout:   "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag

urlweb:       "https://template.vlsm.org/"
urlcontact:   "TBA"
urlgithub:    "https://github.com/ThisIsHowMeDoIt/template"